// savingsRates.js
// Automatycznie generowane przez fetch_savings_rates.py
// Ostatnia aktualizacja: 2026-03-24 02:30
// Źródła: Moneteo.com, Bankier.pl, oficjalne strony banków

export const SAVINGS_RATES_DB = {
  lastUpdated: "2026-03",
  accounts: [
    {
      bank: "BOŚ Bank",
      name: "Konto Oszczędnościowe Cyfrowy Zysk",
      rateStandard: 2.0,
      ratePromo: 7.0,
      promoLimit: 15000,
      promoDays: null,
      promoConditions: "Oferta dla nowych klientów, bez konta osobistego",
      promoConditionsList: [
        "Tylko dla nowych klientów BOŚ Banku",
        "Nie wymaga posiadania konta osobistego",
        "Promocja trwa do 29.04.2026",
        "Limit środków objętych promocją: 15 000 zł",
      ],
      requiresROR: false,
      url: "https://www.bosbank.pl/konto-oszczednosciowe",
    },
    {
      bank: "BNP Paribas",
      name: "Konto Lokacyjne",
      rateStandard: 0.5,
      ratePromo: 7.0,
      promoLimit: 50000,
      promoDays: null,
      promoConditions: "Nowi klienci, konto osobiste, 4 transakcje + wpływy 1000 zł",
      promoConditionsList: [
        "Tylko dla nowych klientów BNP Paribas",
        "Wymagane posiadanie konta osobistego (Konto Otwarte na Ciebie lub Konto Megafon)",
        "Minimum 4 transakcje kartą/BLIK miesięcznie",
        "Wpływ wynagrodzenia min. 1 000 zł/mies.",
        "Promocja trwa do 30.04.2026",
        "Limit środków objętych promocją: 50 000 zł",
      ],
      requiresROR: true,
      url: "https://www.bnpparibas.pl/konto-lokacyjne",
    },
    {
      bank: "Nest Bank",
      name: "Nest Konto Oszczędnościowe",
      rateStandard: 2.0,
      ratePromo: 6.6,
      promoLimit: 25000,
      promoDays: 90,
      promoConditions: "Nowi klienci, wpływ 2000 zł lub 10 transakcji",
      promoConditionsList: [
        "Tylko dla nowych klientów Nest Banku",
        "Wymagane konto osobiste Nest Konto",
        "Wpływ wynagrodzenia min. 2 000 zł/mies. LUB min. 10 transakcji kartą",
        "Okres promocji: 90 dni",
        "Limit środków objętych promocją: 25 000 zł",
      ],
      requiresROR: true,
      url: "https://www.nestbank.pl/konta/konto-oszczednosciowe",
    },
    {
      bank: "VeloBank",
      name: "Elastyczne Konto Oszczędnościowe",
      rateStandard: 1.0,
      ratePromo: 6.0,
      promoLimit: 50000,
      promoDays: 92,
      promoConditions: "Nowi klienci, 5 transakcji/mies.",
      promoConditionsList: [
        "Tylko dla nowych klientów VeloBanku",
        "Wymagane konto osobiste VeloKonto",
        "Minimum 5 transakcji kartą/BLIK miesięcznie",
        "Okres promocji: 92 dni",
        "Limit środków objętych promocją: 50 000 zł",
      ],
      requiresROR: true,
      url: "https://www.velobank.pl/konta/konto-oszczednosciowe",
    },
    {
      bank: "ING Bank Śląski",
      name: "Otwarte Konto Oszczędnościowe",
      rateStandard: 0.8,
      ratePromo: 5.5,
      promoLimit: 400000,
      promoDays: 90,
      promoConditions: "Bonus na start, 3 logowania + 15 transakcji",
      promoConditionsList: [
        "Oferta dla nowych klientów ING (Bonus na start)",
        "Wymagane konto osobiste ING Direct",
        "Minimum 3 logowania do bankowości internetowej/mies.",
        "Minimum 15 transakcji kartą/BLIK miesięcznie",
        "Okres promocji: 90 dni",
        "Limit środków objętych promocją: 400 000 zł",
      ],
      requiresROR: true,
      url: "https://www.ing.pl/indywidualni/oszczedzanie/konto-oszczednosciowe",
    },
    {
      bank: "mBank",
      name: "Moje Cele",
      rateStandard: 0.5,
      ratePromo: 5.3,
      promoLimit: 50000,
      promoDays: 90,
      promoConditions: "Nowi klienci mKonto Intensive",
      promoConditionsList: [
        "Tylko dla nowych klientów mBanku",
        "Wymagane konto mKonto Intensive",
        "Okres promocji: 90 dni",
        "Limit środków objętych promocją: 50 000 zł",
      ],
      requiresROR: true,
      url: "https://www.mbank.pl/indywidualny/oszczednosci/moje-cele/",
    },
    {
      bank: "Alior Bank",
      name: "Konto Oszczędnościowe na Start",
      rateStandard: 1.0,
      ratePromo: 5.2,
      promoLimit: 30000,
      promoDays: 120,
      promoConditions: "Nowi klienci, transakcje 500 zł/mies.",
      promoConditionsList: [
        "Tylko dla nowych klientów Alior Banku",
        "Wymagane konto osobiste",
        "Transakcje kartą na min. 500 zł/mies.",
        "Okres promocji: 120 dni",
        "Limit środków objętych promocją: 30 000 zł",
      ],
      requiresROR: true,
      url: "https://www.aliorbank.pl/indywidualni/oszczednosci/konto-oszczednosciowe.html",
    },
    {
      bank: "Bank Pekao SA",
      name: "Konto Oszczędnościowe",
      rateStandard: 0.5,
      ratePromo: 5.0,
      promoLimit: 100000,
      promoDays: 92,
      promoConditions: "Nowi klienci lub niskie saldo",
      promoConditionsList: [
        "Dla nowych klientów Banku Pekao lub klientów z niskim saldem",
        "Wymagane konto osobiste Konto Przekorzystne lub Eurokonto",
        "Okres promocji: 92 dni",
        "Limit środków objętych promocją: 100 000 zł",
      ],
      requiresROR: true,
      url: "https://www.pekao.com.pl/konto-oszczednosciowe.html",
    },
    {
      bank: "Bank Millennium",
      name: "Konto Oszczędnościowe Profit",
      rateStandard: 0.75,
      ratePromo: 5.0,
      promoLimit: 200000,
      promoDays: 91,
      promoConditions: "Nowe środki, 5 transakcji/mies.",
      promoConditionsList: [
        "Dotyczy nowych środków (ponad dotychczasowe saldo)",
        "Wymagane konto osobiste Millennium 360°",
        "Minimum 5 transakcji kartą/BLIK miesięcznie",
        "Okres promocji: 91 dni",
        "Limit środków objętych promocją: 200 000 zł",
      ],
      requiresROR: true,
      url: "https://www.bankmillennium.pl/konta/konto-oszczednosciowe-profit",
    },
    {
      bank: "Toyota Bank",
      name: "Konto Oszczędnościowe",
      rateStandard: 5.0,
      ratePromo: null,
      promoLimit: null,
      promoDays: null,
      promoConditions: "Dla kwot 50-400 tys. zł",
      promoConditionsList: [
        "Stała stawka 5% bez okresu promocyjnego",
        "Minimalne saldo: 50 000 zł",
        "Maksymalne saldo objęte stawką: 400 000 zł",
        "Wymagane konto osobiste Toyota Bank",
      ],
      requiresROR: true,
      url: "https://www.toyotabank.pl/konto-oszczednosciowe",
    },
    {
      bank: "Nest Bank",
      name: "Nest Konto Twoje Cele",
      rateStandard: 2.0,
      ratePromo: 5.0,
      promoLimit: 20000,
      promoDays: 90,
      promoConditions: null,
      promoConditionsList: [
        "Wymagane konto osobiste Nest Konto",
        "Okres promocji: 90 dni",
        "Limit środków objętych promocją: 20 000 zł",
      ],
      requiresROR: true,
      url: "https://www.nestbank.pl/konta/konto-twoje-cele",
    },
    {
      bank: "VeloBank",
      name: "Elastyczne Konto Oszczędnościowe (nowe środki)",
      rateStandard: 1.0,
      ratePromo: 5.0,
      promoLimit: 100000,
      promoDays: 92,
      promoConditions: "Oferta na nowe środki, 5 transakcji/mies.",
      promoConditionsList: [
        "Dotyczy nowych środków (ponad dotychczasowe saldo)",
        "Wymagane konto osobiste VeloKonto",
        "Minimum 5 transakcji kartą/BLIK miesięcznie",
        "Okres promocji: 92 dni",
        "Limit środków objętych promocją: 100 000 zł",
      ],
      requiresROR: true,
      url: "https://www.velobank.pl/konta/konto-oszczednosciowe",
    },
    {
      bank: "ING Bank Śląski",
      name: "OKO Bonus (nowe środki)",
      rateStandard: 0.8,
      ratePromo: 5.0,
      promoLimit: 400000,
      promoDays: 90,
      promoConditions: "Nowe środki, 3 logowania + 15 transakcji",
      promoConditionsList: [
        "Dotyczy nowych środków (ponad dotychczasowe saldo)",
        "Wymagane konto osobiste ING Direct",
        "Minimum 3 logowania do bankowości internetowej/mies.",
        "Minimum 15 transakcji kartą/BLIK miesięcznie",
        "Okres promocji: 90 dni",
        "Limit środków objętych promocją: 400 000 zł",
      ],
      requiresROR: true,
      url: "https://www.ing.pl/indywidualni/oszczedzanie/konto-oszczednosciowe",
    },
    {
      bank: "UniCredit",
      name: "Konto Oszczędnościowe",
      rateStandard: 4.5,
      ratePromo: null,
      promoLimit: null,
      promoDays: null,
      promoConditions: null,
      promoConditionsList: [
        "Stała stawka 4,5% bez okresu promocyjnego",
        "Brak wymogu konta osobistego",
        "Brak minimalnego salda",
      ],
      requiresROR: false,
      url: "https://www.unicredit.pl/pl/klienci-indywidualni/oszczednosci/konto-oszczednosciowe.html",
    },
    {
      bank: "ING Bank Śląski",
      name: "Smart Saver",
      rateStandard: 4.3,
      ratePromo: null,
      promoLimit: null,
      promoDays: null,
      promoConditions: "Bez warunków",
      promoConditionsList: [
        "Stała stawka 4,3% bez dodatkowych warunków",
        "Brak wymogu konta osobistego",
        "Brak limitu kwoty",
      ],
      requiresROR: false,
      url: "https://www.ing.pl/indywidualni/oszczedzanie/smart-saver",
    },
    {
      bank: "Citi Handlowy",
      name: "Konto Oszczędnościowe",
      rateStandard: 0.8,
      ratePromo: 4.8,
      promoLimit: null,
      promoDays: 180,
      promoConditions: "Citigold, min. 400 tys. zł, 3 transakcje 500 zł/mies.",
      promoConditionsList: [
        "Wymaga statusu Citigold (aktywa min. 400 000 zł)",
        "Wymagane konto osobiste Citi Handlowy",
        "Minimum 3 transakcje po min. 500 zł/mies.",
        "Okres promocji: 180 dni",
      ],
      requiresROR: true,
      url: "https://www.citibank.pl/pl/konto-oszczednosciowe.html",
    },
    {
      bank: "Alior Bank",
      name: "Konto Mega Oszczędnościowe",
      rateStandard: 1.0,
      ratePromo: 4.8,
      promoLimit: 200000,
      promoDays: 90,
      promoConditions: "Nowe środki, transakcje 500 zł/mies.",
      promoConditionsList: [
        "Dotyczy nowych środków (ponad dotychczasowe saldo)",
        "Wymagane konto osobiste Alior Banku",
        "Transakcje kartą na min. 500 zł/mies.",
        "Okres promocji: 90 dni",
        "Limit środków objętych promocją: 200 000 zł",
      ],
      requiresROR: true,
      url: "https://www.aliorbank.pl/indywidualni/oszczednosci/konto-mega-oszczednosciowe.html",
    },
    {
      bank: "Santander Bank Polska",
      name: "Konto Select Oszczędnościowe",
      rateStandard: 1.0,
      ratePromo: 4.0,
      promoLimit: null,
      promoDays: null,
      promoConditions: "Nowe środki",
      promoConditionsList: [
        "Dotyczy nowych środków (ponad dotychczasowe saldo)",
        "Wymagane konto osobiste Santander Select",
        "Brak limitu kwoty",
      ],
      requiresROR: true,
      url: "https://www.santander.pl/klient-indywidualny/konta/konto-oszczednosciowe",
    },
    {
      bank: "Renault Bank",
      name: "Konto Oszczędnościowe",
      rateStandard: 4.0,
      ratePromo: null,
      promoLimit: null,
      promoDays: null,
      promoConditions: null,
      promoConditionsList: [
        "Stała stawka 4% bez okresu promocyjnego",
        "Brak wymogu konta osobistego",
        "Brak minimalnego salda",
      ],
      requiresROR: false,
      url: "https://www.renaultbank.pl/oszczednosci/konto-oszczednosciowe",
    },
    {
      bank: "Credit Agricole",
      name: "Konto Oszczędnościowe",
      rateStandard: 0.5,
      ratePromo: 3.5,
      promoLimit: 100000,
      promoDays: 90,
      promoConditions: "Nowi klienci",
      promoConditionsList: [
        "Tylko dla nowych klientów Credit Agricole",
        "Wymagane konto osobiste CA",
        "Okres promocji: 90 dni",
        "Limit środków objętych promocją: 100 000 zł",
      ],
      requiresROR: true,
      url: "https://www.credit-agricole.pl/klienci-indywidualni/konta/konto-oszczednosciowe",
    },
    {
      bank: "Bank Millennium",
      name: "Konto Twój Cel",
      rateStandard: 0.75,
      ratePromo: 2.75,
      promoLimit: 25000,
      promoDays: null,
      promoConditions: "Wpłata min. 100 zł/mies. zwiększająca saldo",
      promoConditionsList: [
        "Wymagane konto osobiste Millennium 360°",
        "Regularna wpłata min. 100 zł/mies. zwiększająca saldo",
        "Limit środków objętych stawką: 25 000 zł",
      ],
      requiresROR: true,
      url: "https://www.bankmillennium.pl/konta/konto-twoj-cel",
    },
    {
      bank: "Nest Bank",
      name: "Nest Konto Oszczędnościowe (po promocji)",
      rateStandard: 2.0,
      ratePromo: null,
      promoLimit: null,
      promoDays: null,
      promoConditions: "Stawka standardowa po okresie promocji",
      promoConditionsList: [
        "Stawka standardowa obowiązująca po zakończeniu promocji",
        "Wymagane konto osobiste Nest Konto",
      ],
      requiresROR: true,
      url: "https://www.nestbank.pl/konta/konto-oszczednosciowe",
    },
    {
      bank: "VeloBank",
      name: "VeloSkarbonka",
      rateStandard: 1.83,
      ratePromo: null,
      promoLimit: null,
      promoDays: null,
      promoConditions: null,
      promoConditionsList: [
        "Stała stawka 1,83% bez dodatkowych warunków",
        "Brak wymogu konta osobistego",
        "Brak limitu kwoty",
      ],
      requiresROR: false,
      url: "https://www.velobank.pl/konta/veloskarbonka",
    },
    {
      bank: "PKO BP",
      name: "Konto Oszczędnościowe",
      rateStandard: 0.5,
      ratePromo: null,
      promoLimit: null,
      promoDays: null,
      promoConditions: null,
      promoConditionsList: [
        "Wymagane konto osobiste PKO BP",
        "Stawka standardowa 0,5%",
      ],
      requiresROR: true,
      url: "https://www.pkobp.pl/klienci-indywidualni/konta/konto-oszczednosciowe/",
    },
    {
      bank: "mBank",
      name: "eKonto Oszczędnościowe",
      rateStandard: 0.5,
      ratePromo: null,
      promoLimit: null,
      promoDays: null,
      promoConditions: null,
      promoConditionsList: [
        "Wymagane konto osobiste mKonto",
        "Stawka standardowa 0,5%",
      ],
      requiresROR: true,
      url: "https://www.mbank.pl/indywidualny/oszczednosci/ekonto-oszczednosciowe/",
    },
  ],
};
