// savingsRates.js
// Automatycznie generowane przez fetch_savings_rates.py
// Ostatnia aktualizacja: 2026-03-24 02:30
// Źródła: Moneteo.com, Bankier.pl, oficjalne strony banków

export const SAVINGS_RATES_DB = {
  lastUpdated: "2026-03",
  accounts: [
    {
      bank: "BOŚ Bank",
      name: "Konto Oszczędnościowe Cyfrowy Zysk",
      rateStandard: 2.0,
      ratePromo: 7.0,
      promoLimit: 15000,
      promoDays: null,
      promoConditions: "Oferta dla nowych klientów, bez konta osobistego",
      requiresROR: false,
    },
    {
      bank: "BNP Paribas",
      name: "Konto Lokacyjne",
      rateStandard: 0.5,
      ratePromo: 7.0,
      promoLimit: 50000,
      promoDays: null,
      promoConditions: "Nowi klienci, konto osobiste, 4 transakcje + wpływy 1000 zł",
      requiresROR: true,
    },
    {
      bank: "Nest Bank",
      name: "Nest Konto Oszczędnościowe",
      rateStandard: 2.0,
      ratePromo: 6.6,
      promoLimit: 25000,
      promoDays: 90,
      promoConditions: "Nowi klienci, wpływ 2000 zł lub 10 transakcji",
      requiresROR: true,
    },
    {
      bank: "VeloBank",
      name: "Elastyczne Konto Oszczędnościowe",
      rateStandard: 1.0,
      ratePromo: 6.0,
      promoLimit: 50000,
      promoDays: 92,
      promoConditions: "Nowi klienci, 5 transakcji/mies.",
      requiresROR: true,
    },
    {
      bank: "ING Bank Śląski",
      name: "Otwarte Konto Oszczędnościowe",
      rateStandard: 0.8,
      ratePromo: 5.5,
      promoLimit: 400000,
      promoDays: 90,
      promoConditions: "Bonus na start, 3 logowania + 15 transakcji",
      requiresROR: true,
    },
    {
      bank: "mBank",
      name: "Moje Cele",
      rateStandard: 0.5,
      ratePromo: 5.3,
      promoLimit: 50000,
      promoDays: 90,
      promoConditions: "Nowi klienci mKonto Intensive",
      requiresROR: true,
    },
    {
      bank: "Alior Bank",
      name: "Konto Oszczędnościowe na Start",
      rateStandard: 1.0,
      ratePromo: 5.2,
      promoLimit: 30000,
      promoDays: 120,
      promoConditions: "Nowi klienci, transakcje 500 zł/mies.",
      requiresROR: true,
    },
    {
      bank: "Bank Pekao SA",
      name: "Konto Oszczędnościowe",
      rateStandard: 0.5,
      ratePromo: 5.0,
      promoLimit: 100000,
      promoDays: 92,
      promoConditions: "Nowi klienci lub niskie saldo",
      requiresROR: true,
    },
    {
      bank: "Bank Millennium",
      name: "Konto Oszczędnościowe Profit",
      rateStandard: 0.75,
      ratePromo: 5.0,
      promoLimit: 200000,
      promoDays: 91,
      promoConditions: "Nowe środki, 5 transakcji/mies.",
      requiresROR: true,
    },
    {
      bank: "Toyota Bank",
      name: "Konto Oszczędnościowe",
      rateStandard: 5.0,
      ratePromo: null,
      promoLimit: null,
      promoDays: null,
      promoConditions: "Dla kwot 50-400 tys. zł",
      requiresROR: true,
    },
    {
      bank: "Nest Bank",
      name: "Nest Konto Twoje Cele",
      rateStandard: 2.0,
      ratePromo: 5.0,
      promoLimit: 20000,
      promoDays: 90,
      promoConditions: null,
      requiresROR: true,
    },
    {
      bank: "VeloBank",
      name: "Elastyczne Konto Oszczędnościowe (nowe środki)",
      rateStandard: 1.0,
      ratePromo: 5.0,
      promoLimit: 100000,
      promoDays: 92,
      promoConditions: "Oferta na nowe środki, 5 transakcji/mies.",
      requiresROR: true,
    },
    {
      bank: "ING Bank Śląski",
      name: "OKO Bonus (nowe środki)",
      rateStandard: 0.8,
      ratePromo: 5.0,
      promoLimit: 400000,
      promoDays: 90,
      promoConditions: "Nowe środki, 3 logowania + 15 transakcji",
      requiresROR: true,
    },
    {
      bank: "Citi Handlowy",
      name: "Konto Oszczędnościowe",
      rateStandard: 0.8,
      ratePromo: 4.8,
      promoLimit: null,
      promoDays: 180,
      promoConditions: "Citigold, min. 400 tys. zł, 3 transakcje 500 zł/mies.",
      requiresROR: true,
    },
    {
      bank: "Alior Bank",
      name: "Konto Mega Oszczędnościowe",
      rateStandard: 1.0,
      ratePromo: 4.8,
      promoLimit: 200000,
      promoDays: 90,
      promoConditions: "Nowe środki, transakcje 500 zł/mies.",
      requiresROR: true,
    },
    {
      bank: "UniCredit",
      name: "Konto Oszczędnościowe",
      rateStandard: 4.5,
      ratePromo: null,
      promoLimit: null,
      promoDays: null,
      promoConditions: null,
      requiresROR: false,
    },
    {
      bank: "ING Bank Śląski",
      name: "Smart Saver",
      rateStandard: 4.3,
      ratePromo: null,
      promoLimit: null,
      promoDays: null,
      promoConditions: "Bez warunków",
      requiresROR: false,
    },
    {
      bank: "Santander Bank Polska",
      name: "Konto Select Oszczędnościowe",
      rateStandard: 1.0,
      ratePromo: 4.0,
      promoLimit: null,
      promoDays: null,
      promoConditions: "Nowe środki",
      requiresROR: true,
    },
    {
      bank: "Renault Bank",
      name: "Konto Oszczędnościowe",
      rateStandard: 4.0,
      ratePromo: null,
      promoLimit: null,
      promoDays: null,
      promoConditions: null,
      requiresROR: false,
    },
    {
      bank: "Credit Agricole",
      name: "Konto Oszczędnościowe",
      rateStandard: 0.5,
      ratePromo: 3.5,
      promoLimit: 100000,
      promoDays: 90,
      promoConditions: "Nowi klienci",
      requiresROR: true,
    },
    {
      bank: "Bank Millennium",
      name: "Konto Twój Cel",
      rateStandard: 0.75,
      ratePromo: 2.75,
      promoLimit: 25000,
      promoDays: null,
      promoConditions: "Wpłata min. 100 zł/mies. zwiększająca saldo",
      requiresROR: true,
    },
    {
      bank: "Nest Bank",
      name: "Nest Konto Oszczędnościowe (po promocji)",
      rateStandard: 2.0,
      ratePromo: null,
      promoLimit: null,
      promoDays: null,
      promoConditions: "Stawka standardowa po okresie promocji",
      requiresROR: true,
    },
    {
      bank: "VeloBank",
      name: "VeloSkarbonka",
      rateStandard: 1.83,
      ratePromo: null,
      promoLimit: null,
      promoDays: null,
      promoConditions: null,
      requiresROR: false,
    },
    {
      bank: "PKO BP",
      name: "Konto Oszczędnościowe",
      rateStandard: 0.5,
      ratePromo: null,
      promoLimit: null,
      promoDays: null,
      promoConditions: null,
      requiresROR: true,
    },
    {
      bank: "mBank",
      name: "eKonto Oszczędnościowe",
      rateStandard: 0.5,
      ratePromo: null,
      promoLimit: null,
      promoDays: null,
      promoConditions: null,
      requiresROR: true,
    },
  ],
};
