// savingsRates.js
// Automatycznie generowane przez fetch_savings_rates.py
// Ostatnia aktualizacja: 2026-04-13 12:12
// Źródła: Moneteo.com, Bankier.pl, Comperia.pl, oficjalne strony banków

export const SAVINGS_RATES_DB = {
  lastUpdated: "2026-04",
  accounts: [
    {
      bank: "BOŚ Bank",
      name: "Konto Oszczędnościowe Cyfrowy Zysk",
      rateStandard: 2.0,
      ratePromo: 7.0,
      promoLimit: 15000,
      promoDays: null,
      promoEndDate: "2026-04-29",
      promoConditions: "Oferta dla nowych klientów, bez konta osobistego",
      promoConditionsList: ["Tylko dla nowych klientów BOŚ Banku", "Nie wymaga posiadania konta osobistego", "Limit środków objętych promocją: 15 000 zł", "Oferta ważna do 29.04.2026"],
      requiresROR: false,
      isNew: true,
      addedDate: "2026-04-07",
      url: "https://www.bosbank.pl/klient-indywidualny/oszczednosci/konta-oszczednosciowe/konto-oszczednosciowe-cyfrowy-zysk",
    },
    {
      bank: "BNP Paribas",
      name: "Konto Lokacyjne",
      rateStandard: 0.5,
      ratePromo: 7.0,
      promoLimit: 50000,
      promoDays: null,
      promoEndDate: "2026-04-30",
      promoConditions: "Nowi klienci, konto osobiste, 4 transakcje + wpływy 1000 zł",
      promoConditionsList: ["Tylko dla nowych klientów BNP Paribas", "Wymagane konto osobiste", "Min. 4 transakcje kartą/BLIK miesięcznie", "Wpływ wynagrodzenia min. 1 000 zł/mies.", "Limit: 50 000 zł", "Oferta ważna do 30.04.2026"],
      requiresROR: true,
      isNew: true,
      addedDate: "2026-04-07",
      url: "https://www.bnpparibas.pl/klienci-indywidualni/oszczednosci-i-inwestycje/konto-lokacyjne",
    },
    {
      bank: "Nest Bank",
      name: "Nest Konto Oszczędnościowe",
      rateStandard: 2.0,
      ratePromo: 6.6,
      promoLimit: 25000,
      promoDays: 90,
      promoEndDate: null,
      promoConditions: "Nowi klienci, wpływ 2000 zł lub 10 transakcji",
      promoConditionsList: ["Tylko dla nowych klientów Nest Banku", "Wymagane konto osobiste Nest Konto", "Wpływ min. 2 000 zł/mies. LUB min. 10 transakcji kartą", "Okres promocji: 90 dni", "Limit: 25 000 zł"],
      requiresROR: true,
      isNew: true,
      addedDate: "2026-04-13",
      url: "https://nestbank.pl/nest-konto-oszczednosciowe/",
    },
    {
      bank: "VeloBank",
      name: "Elastyczne Konto Oszczędnościowe",
      rateStandard: 1.0,
      ratePromo: 6.0,
      promoLimit: 50000,
      promoDays: 92,
      promoEndDate: null,
      promoConditions: "Nowi klienci, 5 transakcji/mies.",
      promoConditionsList: ["Tylko dla nowych klientów VeloBanku", "Wymagane konto osobiste VeloKonto", "Min. 5 transakcji kartą/BLIK miesięcznie", "Okres promocji: 92 dni", "Limit: 50 000 zł"],
      requiresROR: true,
      isNew: true,
      addedDate: "2026-04-13",
      url: "https://www.velobank.pl/bankowosc-premium/oszczednosci/konto-oszczednosciowe.html",
    },
    {
      bank: "ING Bank Śląski",
      name: "Otwarte Konto Oszczędnościowe",
      rateStandard: 0.8,
      ratePromo: 5.5,
      promoLimit: 400000,
      promoDays: 90,
      promoEndDate: null,
      promoConditions: "Bonus na start, 3 logowania + 15 transakcji",
      promoConditionsList: ["Oferta dla nowych klientów ING (Bonus na start)", "Wymagane konto osobiste ING Direct", "Min. 3 logowania do bankowości internetowej/mies.", "Min. 15 transakcji kartą/BLIK miesięcznie", "Okres promocji: 90 dni", "Limit: 400 000 zł"],
      requiresROR: true,
      isNew: true,
      addedDate: "2026-04-13",
      url: "https://www.ing.pl/indywidualni/inwestycje-i-oszczednosci/otwarte-konto-oszczednosciowe-bonus",
    },
    {
      bank: "mBank",
      name: "Moje Cele",
      rateStandard: 0.5,
      ratePromo: 5.3,
      promoLimit: 50000,
      promoDays: 90,
      promoEndDate: null,
      promoConditions: "Nowi klienci mKonto Intensive",
      promoConditionsList: ["Tylko dla nowych klientów mBanku", "Wymagane konto mKonto Intensive", "Okres promocji: 90 dni", "Limit: 50 000 zł"],
      requiresROR: true,
      isNew: true,
      addedDate: "2026-04-13",
      url: "https://www.mbank.pl/indywidualny/inwestycje-i-oszczednosci/regularne-odkladanie/ekonto-oszczednosciowe/",
    },
    {
      bank: "Alior Bank",
      name: "Konto Oszczędnościowe na Start",
      rateStandard: 1.0,
      ratePromo: 5.2,
      promoLimit: 30000,
      promoDays: 120,
      promoEndDate: null,
      promoConditions: "Nowi klienci, transakcje 500 zł/mies.",
      promoConditionsList: ["Tylko dla nowych klientów Alior Banku", "Wymagane konto osobiste", "Transakcje kartą na min. 500 zł/mies.", "Okres promocji: 120 dni", "Limit: 30 000 zł"],
      requiresROR: true,
      isNew: true,
      addedDate: "2026-04-13",
      url: "https://www.aliorbank.pl",
    },
    {
      bank: "Bank Pekao SA",
      name: "Konto Oszczędnościowe",
      rateStandard: 0.5,
      ratePromo: 5.0,
      promoLimit: 100000,
      promoDays: 92,
      promoEndDate: null,
      promoConditions: "Nowi klienci lub niskie saldo",
      promoConditionsList: ["Dla nowych klientów lub klientów z niskim saldem", "Wymagane konto osobiste Pekao", "Okres promocji: 92 dni", "Limit: 100 000 zł"],
      requiresROR: true,
      isNew: true,
      addedDate: "2026-04-13",
      url: "https://www.pekao.com.pl/klient-indywidualny/oszczedzam-i-inwestuje/programy-oszczednosciowe/konto-oszczednosciowe.html",
    },
    {
      bank: "Bank Millennium",
      name: "Konto Oszczędnościowe Profit",
      rateStandard: 0.75,
      ratePromo: 5.0,
      promoLimit: 200000,
      promoDays: 91,
      promoEndDate: null,
      promoConditions: "Nowe środki, 5 transakcji/mies.",
      promoConditionsList: ["Dotyczy nowych środków (ponad dotychczasowe saldo)", "Wymagane konto osobiste Millennium 360°", "Min. 5 transakcji kartą/BLIK miesięcznie", "Okres promocji: 91 dni", "Limit: 200 000 zł"],
      requiresROR: true,
      isNew: true,
      addedDate: "2026-04-13",
      url: "https://www.bankmillennium.pl/klienci-indywidualni/produkty-oszczednosciowe/rachunki-oszczednosciowe/konto-oszczednosciowe-profit",
    },
    {
      bank: "Toyota Bank",
      name: "Konto Oszczędnościowe",
      rateStandard: 5.0,
      ratePromo: null,
      promoLimit: null,
      promoDays: null,
      promoEndDate: null,
      promoConditions: "Dla kwot 50-400 tys. zł",
      promoConditionsList: ["Stała stawka 5% bez okresu promocyjnego", "Minimalne saldo: 50 000 zł", "Maksymalne saldo objęte stawką: 400 000 zł"],
      requiresROR: true,
      isNew: true,
      addedDate: "2026-04-13",
      url: "https://www.toyotabank.pl/konto-oszczednosciowe",
    },
    {
      bank: "Citi Handlowy",
      name: "Konto Oszczędnościowe",
      rateStandard: 0.8,
      ratePromo: 4.8,
      promoLimit: null,
      promoDays: 180,
      promoEndDate: null,
      promoConditions: "Citigold, min. 400 tys. zł, 3 transakcje 500 zł/mies.",
      promoConditionsList: ["Wymaga statusu Citigold (aktywa min. 400 000 zł)", "Min. 3 transakcje po min. 500 zł/mies.", "Okres promocji: 180 dni"],
      requiresROR: true,
      isNew: true,
      addedDate: "2026-04-13",
      url: "https://www.citibank.pl/konta-osobiste/produkty-oszczednosciowe/konto-superoszczednosciowe/",
    },
    {
      bank: "Alior Bank",
      name: "Konto Mega Oszczędnościowe",
      rateStandard: 1.0,
      ratePromo: 4.8,
      promoLimit: 200000,
      promoDays: 90,
      promoEndDate: null,
      promoConditions: "Nowe środki, transakcje 500 zł/mies.",
      promoConditionsList: ["Dotyczy nowych środków", "Transakcje kartą na min. 500 zł/mies.", "Okres promocji: 90 dni", "Limit: 200 000 zł"],
      requiresROR: true,
      isNew: true,
      addedDate: "2026-04-13",
      url: "https://www.aliorbank.pl",
    },
    {
      bank: "UniCredit",
      name: "Konto Oszczędnościowe",
      rateStandard: 4.5,
      ratePromo: null,
      promoLimit: null,
      promoDays: null,
      promoEndDate: null,
      promoConditions: null,
      promoConditionsList: ["Stała stawka 4,5% bez okresu promocyjnego", "Brak wymogu konta osobistego"],
      requiresROR: false,
      isNew: true,
      addedDate: "2026-04-13",
      url: "https://www.unicredit.pl/indywidualni/oszczednosci/konto-oszczednosciowe",
    },
    {
      bank: "ING Bank Śląski",
      name: "Smart Saver",
      rateStandard: 4.3,
      ratePromo: null,
      promoLimit: null,
      promoDays: null,
      promoEndDate: null,
      promoConditions: "Bez warunków",
      promoConditionsList: ["Stała stawka 4,3% bez dodatkowych warunków", "Brak wymogu konta osobistego"],
      requiresROR: false,
      isNew: true,
      addedDate: "2026-04-13",
      url: "https://www.ing.pl/indywidualni/inwestycje-i-oszczednosci/smart-saver",
    },
    {
      bank: "Santander Bank Polska",
      name: "Konto Select Oszczędnościowe",
      rateStandard: 1.0,
      ratePromo: 4.0,
      promoLimit: null,
      promoDays: null,
      promoEndDate: null,
      promoConditions: "Nowe środki",
      promoConditionsList: ["Dotyczy nowych środków", "Wymagane konto osobiste Santander Select"],
      requiresROR: true,
      isNew: true,
      addedDate: "2026-04-13",
      url: "https://www.santander.pl/select/oszczednosci-i-inwestycje/konto-oszczednosciowe-select",
    },
    {
      bank: "Renault Bank",
      name: "Konto Oszczędnościowe",
      rateStandard: 4.0,
      ratePromo: null,
      promoLimit: null,
      promoDays: null,
      promoEndDate: null,
      promoConditions: null,
      promoConditionsList: ["Stała stawka 4% bez okresu promocyjnego", "Brak wymogu konta osobistego"],
      requiresROR: false,
      isNew: true,
      addedDate: "2026-04-13",
      url: "https://www.raisin.com",
    },
    {
      bank: "Credit Agricole",
      name: "Konto Oszczędnościowe",
      rateStandard: 0.5,
      ratePromo: 3.5,
      promoLimit: 100000,
      promoDays: 90,
      promoEndDate: null,
      promoConditions: "Nowi klienci",
      promoConditionsList: ["Tylko dla nowych klientów Credit Agricole", "Wymagane konto osobiste CA", "Okres promocji: 90 dni", "Limit: 100 000 zł"],
      requiresROR: true,
      isNew: true,
      addedDate: "2026-04-13",
      url: "https://www.credit-agricole.pl/klienci-indywidualni/oszczednosci/rachunek-oszczedzam",
    },
    {
      bank: "PKO BP",
      name: "Konto Oszczędnościowe",
      rateStandard: 0.5,
      ratePromo: null,
      promoLimit: null,
      promoDays: null,
      promoEndDate: null,
      promoConditions: null,
      promoConditionsList: ["Wymagane konto osobiste PKO BP", "Stawka standardowa 0,5%"],
      requiresROR: true,
      isNew: true,
      addedDate: "2026-04-13",
      url: "https://www.pkobp.pl/klient-indywidualny/konta/konto-oszczednosciowe",
    },
    {
      bank: "mBank",
      name: "eKonto Oszczędnościowe",
      rateStandard: 0.5,
      ratePromo: null,
      promoLimit: null,
      promoDays: null,
      promoEndDate: null,
      promoConditions: null,
      promoConditionsList: ["Wymagane konto osobiste mKonto", "Stawka standardowa 0,5%"],
      requiresROR: true,
      isNew: true,
      addedDate: "2026-04-13",
      url: "https://www.mbank.pl/indywidualny/inwestycje-i-oszczednosci/regularne-odkladanie/ekonto-oszczednosciowe/",
    },
  ],
};
